const flatironData = {
  title: 'Flatiron School',
  content: ['In early October of 2022, I graduated from Flatiron School\'s Software Engineering Live program. The program consisted of five three-week phases each of the first four pertaining to JavaScript, React, Ruby/SQL, or Rails, respectively. The fifth phase focused on building a capstone project the combined our understanding of the previous four phases.', 'The program ran the equivalent of 525 clock hours not including additional time spent outside of class on homework or studying.', 'During the course of the program we were exposed to a number of technologies, including versions which were likely to exist in older code bases. For example, we worked with both React Router versions 5 and 6, we used four versions of Ruby in our coursework, and several versions of Rails. Flatiron strongly emphasized the normalcy of working with differing versions of languages and their dependent libraries.', 'Likewise, we were encouraged to develop a complete understanding of git and the critical importance of version control from the outset of the program.', 'My main objective while I was a student at Flatiron was to set down a solid foundation on which to build. I know I have so much to learn and it is exciting the sheer volume of information that exists on even a single language, library or framework. I look forward to building my knowledge with a great company in the near future!']
}

const workData = {
  title: 'Leadership Experience',
  content: ['I have spent half of my seventeen years in the workforce as a supervisor or manager in the mid sized retail consumables industry leading small teams of four to seven. I hope to leverage that experience to become an asset in a role as a software engineer.', 'By far, the most critical role I have played in the success of the companies I have worked for has been in training and team-building. Beyond training a large number of entry level employees, I was responsible for training fully a third of the front-end supervisors in the Minnesota market while I was working for Total Wine & More, including my own replacement when I was promoted. Beyond that, I trained every educator who taught wine and spirits classes out of the Minnetonka store.', 'I firmly believe that an early investment in excellent training pays exceptional dividends down the line. Leveling everyone up and bringing everyone on the team along is far and above the most efficient way to run a team over any serious period of time.', 'I understand that I am at the very bottom rung of the ladder as a software engineer, but I hope to be in the position to help as many junior engineers succeed as possible in a few short years. All I need is a company that has the same strong belief in team member development that I do.']
}

export { flatironData, workData }